describe('admins should be able to login as well as add, edit, or delete other users', () => {
    it('admin should get a list of students and a list of instructors', () => {
        cy.visit('http://localhost:3000/#/admindashboard')
            .wait(1500)
        cy.get('td#8011111111_cell')
            .should('contain','8011111111')

    });
    it('admin can add a user', () => {
        cy.get('button')
            .contains('Add')
            .click()
        cy.get('input#name_input')
            .type('Todd Ross')
        cy.get('input#instructorChoice')
            .check({force:true})
        cy.get('input#input_phone')
            .type(8675309)
        cy.get('input#input_email')
            .type('onlyTheHappiestTrees@bob.ross')
        cy.get('button')
            .contains('Save')
            .click()
        cy.get('td#8675309_cell')
            .should('contain','8675309')
    });
    it('admin can edit a user', () => {
        cy.get('button#8675309')
            .click()
        cy.get('input#name_input')
            .clear()
            .type('Todd Rosssss')
        cy.get('input#studentChoice')
            .check({force:true})
        cy.get('input#input_phone')
            .clear()
            .type(8675308)
        cy.get('input#input_email')
            .clear()
            .type('onlyTheHappiestTrees@bob.ross')
        cy.get('button')
            .contains('Save')
            .click()
        cy.get('td#8675308_cell')
            .should('contain','8675308')
    });
    it('admin should be able to delete a user', () => {
        cy.get('button#8675308')
            .click()
        cy.get('button')
            .contains('Delete')
            .click()
        
    })
})