describe('Instructions should be able to build a curriculum', () => {
    it('Instructors should be able to add a curriculum name', () => {
        cy.visit('http://localhost:3000/#/curriculumbuilder')
        cy.get('input#cb-cur-name')
            .type('Calculus')
        cy.get('input#cb-cur-name')
            .should('have.value', 'Calculus')
        cy.get('button')
            .contains('Save Name')
            .click()
        cy.get('.cb-name-header')
            .should('contain', 'Calculus')
    })

    it('Instructor should be able to add a day', () => {
        cy.get('input[type="number"]')
            .clear()
            .type(2)
        cy.get('button')
            .contains('Set Days')
            .click()
        cy.get('.cb-daysquare')
            .contains('Day 2')
            .should('contain', 'Day 2')
    })

    it('Instructor should be able to add day change the day pane to day 2', () => {
        cy.get('.cb-daysquare')
            .contains('Day 2')
            .click()
        cy.get('div.ui.header')
            .should('contain', 'Day 2')
    })

    it('Instructor should be able to save day information to day 2', () => {
        cy.get('div.cbds-inputs-container > div > div > input[type="text"]')
            .type('Graphing Lines')
        cy.get('div.cbds-inputs-container > div > form > textarea')
            .type('Graphing lines on a graph with lines')
        cy.get('button')
            .contains('Save')
            .click()
        cy.get('.cbds-inputs-container > div > div')
            .should('contain', 'Graphing Lines')
        cy.get('.cbds-inputs-container > div > p')
            .should('contain', 'Graphing lines on a graph with lines')
    })
  
    it('Instructor should be able to edit day text', () => {
        cy.get('.cbds-inputs-container > .primary')
            .contains('Edit')
            .click()
        cy.get('#cb-day-name')
            .clear()
            .type('Nap time')
        cy.get('textarea')
            .clear()
            .type('Some much needed sleep')
        cy.get('.cbds-inputs-container > .primary')
            .contains('Save')
            .click()
        cy.get('.cbds-inputs-container > div > div')
            .should('contain', 'Nap time')
        cy.get('.cbds-inputs-container > div > p')
            .should('contain', 'Some much needed sleep')
        
        
    })
})